apiVersion: v1
kind: Service
metadata:
  name: bouncer-service
  namespace: bouncer
  labels:
    app: bouncer
spec:
  type: ClusterIP
  selector:
    app: bouncer
  ports:
  - name: http
    port: 4444
    targetPort: http
    protocol: TCP
  sessionAffinity: None
