[tools]
go = "1.25"
golangci-lint = "v2.8.0"
"go:mvdan.cc/gofumpt" = "v0.9.2"
"go:golang.org/x/vuln/cmd/govulncheck" = "v1.1.4"
"go:github.com/air-verse/air" = "v1.64.5"
"go:github.com/evilmartians/lefthook/v2" = "v2.1.0"

[tasks.lint]
description = "Lint all apps and packages"
run = "golangci-lint run ./..."

[tasks.format]
description = "Format code strictly"
run = "gofumpt -l -w ."

[tasks.vuln]
description = "Check for vulnerabilities"
run = "govulncheck ./..."

[tasks.setup]
description = "Setup the project"
run = [
  "chmod +x ./scripts/**",
  "mise install",
  "mise run hooks"
]

[tasks.hooks]
description = "Setup hooks"
run = "lefthook install"
