[tools]
go = "1.25"
golangci-lint = "v2.8.0"
typos = "1.43.1"
lychee = "0.22.0"
"go:mvdan.cc/gofumpt" = "v0.9.2"
"go:golang.org/x/vuln/cmd/govulncheck" = "v1.1.4"
"go:github.com/air-verse/air" = "v1.64.5"
"go:github.com/evilmartians/lefthook/v2" = "v2.1.0"

[tasks.lint]
description = "Lint all apps and packages"
run = "./scripts/run-on.sh golangci-lint run"

[tasks.format]
description = "Format code strictly"
run = "gofumpt -l -w ."

[tasks.vuln]
description = "Check for vulnerabilities"
run = "./scripts/run-on.sh govulncheck ./..."


[tasks.test]
description = "Tests the project and its sub apps"
run = './scripts/run-on.sh go test -v ./...'

[tasks.setup]
description = "Setup the project"
run = [
  "chmod +x ./scripts/**",
  "mise install",
  "mise run hooks"
]

[tasks.hooks]
description = "Setup hooks"
run = "lefthook install"

[tasks."farm:build"]
description = "Compiles the farm binary"
run = "go build -o ./apps/farm/bin/farm ./apps/farm/cmd/main.go"

[tasks."hub:build"]
description = "Compiles the hub binary"
run = "go build -o ./apps/hub/bin/hub ./apps/hub/cmd/main.go"

[tasks."farm:dev"]
description = "Runs Farm with live reload"
run = 'air --build.cmd mise run hub:build --build.entrypoint ./apps/hub/bin/hub' 

[tasks."hub:dev"]
description = "Runs Hub with live reload"
run = 'air --build.cmd mise run hub:build --build.entrypoint ./apps/hub/bin/hub' 

