package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/john-eevee/gaia/apps/hub/internal/gql/generated"
	"github.com/john-eevee/gaia/apps/hub/internal/gql/models"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*models.Health, error) {
	return &models.Health{
		Status:  "OK",
		Version: "0.1.0",
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
