name: Farm CI

on:
  push:
    branches: ["main"]
    paths:
      - "apps/farm/**"
      - "pkg/**"
      - "go.work"
  pull_request:
    paths:
      - "apps/farm/**"
      - "pkg/**"
      - "go.work"

jobs:
  # Call the reusable workflow
  ci-pipeline:
    uses: ./.github/workflows/go.jobs.yml
    with:
      app_dir: "apps/farm"
