# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Hub CI

on:
  push:
    branches: ["main"]
    paths:
      - "hub/**"
      - ".github/workflows/elixir.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "hub/**"
      - ".github/workflows/elixir.yml"

permissions:
  contents: read

env:
  MIX_ENV: test

jobs:
  test:
    name: Hub CI Suite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Elixir
        uses: jdx/mise-action@v3
      - name: Setup hex and rebar
        run: mix local.hex --force && mix local.rebar --force
      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v4
        env:
          cache-name: cache-elixir-deps
        with:
          path: hub/deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('hub/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
      - name: Cache compiled build
        id: cache-build
        uses: actions/cache@v4
        env:
          cache-name: cache-compiled-build
        with:
          path: hub/_build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('hub/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
            ${{ runner.os }}-mix-
      - name: Clean to rule out incremental build as a source of flakiness
        if: github.run_attempt != '1'
        run: |
          mix deps.clean --all
          mix clean
        shell: sh
      - name: Run CI
        run: mix ci
