name: Co-op Hub CI

on:
  push:
    branches: ["main"]
    paths:
      - "apps/hub/**"
      - "pkg/**"
      - "go.work"
  pull_request:
    paths:
      - "apps/hub/**"
      - "pkg/**"
      - "go.work"

jobs:
  ci-pipeline:
    uses: ./.github/workflows/go.jobs.yml
    with:
      app_dir: "apps/hub"
